[![Open In Studio Lab](https://studiolab.sagemaker.aws/studiolab.svg)](https://studiolab.sagemaker.aws/import/github/wenh06/buaa-advanced-algebra-2021/blob/master/notebooks/习题.ipynb)
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/wenh06/buaa-advanced-algebra-2021/blob/master/notebooks/习题.ipynb)

In [1]:
import numpy as np
# ^^^ pyforest auto-imports - don't write above this line
import sympy as sp

In [2]:
# !pip install numpy sympy

# 第2章 线性空间

## 习题2.1

### 第 2 题

In [3]:
# (1)
A = np.array([2,0,-1,2,0,-2,1,-3,3,-1,2,1,-2,4,-7,5]).reshape((4,4))
np.linalg.matrix_rank(A)

3

In [4]:
# (2)
A = np.array([1,-1,0,0,0,1,-1,0,0,0,1,-1,-1,0,0,1]).reshape((4,4))
np.linalg.matrix_rank(A)

3

## 习题2.3

### 第1题

In [5]:
mat = np.array([3,1,0,6,3,2,1,3,5]).reshape((3,3)).T
beta = np.array([2,-1,2]).T
np.linalg.solve(mat, beta)

array([-76.,  41., -16.])

### 第3题

In [6]:
alpha = np.array([1,1,1,1,0,1,-1,-1,0,0,1,-1,0,0,0,1]).reshape((4,4)).T
e = np.eye(4)
coeff = np.linalg.inv(alpha) @ e
for idx in range(4):
    print(coeff[:, idx])

[ 1. -1. -2. -4.]
[0. 1. 1. 2.]
[0. 0. 1. 1.]
[0. 0. 0. 1.]


### 第4题

In [7]:
# (1)
mat = sp.Matrix(np.array([1,1,1,1,1,1,2,3,4,5,1,0,-1,-2,-3]).reshape(3,5))
b = sp.Matrix(np.zeros((3,1)))

x, params, free_var_index = mat.gauss_jordan_solve(b, freevar=True)
x

Matrix([
[   tau0 + 2*tau1 + 3*tau2],
[-2*tau0 - 3*tau1 - 4*tau2],
[                     tau0],
[                     tau1],
[                     tau2]])

In [8]:
# (2)
mat = sp.Matrix(np.array([1,1,1,1,-4,1,-2,3,-4,2,-1,3,-5,7,-4,1,2,-1,4,-6]).reshape(4,5))
b = sp.Matrix(np.zeros((4,1)))

x, params, free_var_index = mat.gauss_jordan_solve(b, freevar=True)
x

Matrix([
[-tau0 + 2*tau1],
[-tau0 + 2*tau1],
[          tau0],
[          tau0],
[          tau1]])

### 第5题

In [9]:
X = sp.Matrix(np.array([1,2,3,4,5,1,-1,1,-1,1,1,2,4,8,16]).reshape(3,5))
b = sp.Matrix(np.zeros((3,1)))

A, params, free_var_index = X.gauss_jordan_solve(b, freevar=True)
A

Matrix([
[ 6*tau0 + 16*tau1],
[    tau0 + 6*tau1],
[-4*tau0 - 11*tau1],
[             tau0],
[             tau1]])

## 习题2.4

### 第1题

In [10]:
X = np.array([1,1,1,1,1,1,2,3,4,5,1,0,-3,-2,-3]).reshape((3,5))
np.linalg.matrix_rank(X)

3